import Footer from "@/components/Footer";
import Header from "@/components/Header";
import PrelineScript from "@/components/PrelineScript";
import AuthProvider from "@/context/AuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.className} bg-[#F7EFE5]`}>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </AuthProvider>

      <PrelineScript />
    </html>
  );
}
